
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: concierge
      POSTGRES_USER: concierge_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"  

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concierge_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .          
      dockerfile: backend/Dockerfile  
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - web

volumes:
  postgres_data:
