# Generated by Django 5.1.8 on 2025-04-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tenant_type',
            field=models.CharField(choices=[('management_office', 'Management Office'), ('other', 'Other')], default='management_office', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
