# Generated by Django 5.1.8 on 2025-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_tenant_type_alter_client_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tenant_type',
            field=models.CharField(choices=[('management_office', 'Management Office'), ('other', 'Other Client')], default='management_office', max_length=50),
        ),
    ]
