# 📄 votes/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import VoteViewSet

router = DefaultRouter()
router.register(r'votes', VoteViewSet, basename='vote')

urlpatterns = [
    path('', include(router.urls)),
]
# This code sets up the URL routing for the votes app in a Django project. It uses Django REST Framework's DefaultRouter to automatically generate the necessary URL patterns for the VoteViewSet, which handles CRUD operations for votes. The urlpatterns list includes a path that includes all the URLs generated by the router.
# This allows the API to handle requests to the /votes endpoint, where users can create, retrieve, update, and delete votes.
